### ISSUE TITLE
Story: Create projects and assign Blocks

### ISSUE THREAD

**Issue by bastianbc** [bastianbc/BastianLab#30]
Process for accessioning tissues (blocks) to projects

**Comment by bastianbc** [comment]
[Create project and assign blocks.docx](https://github.com/bastianbc/BastianLab/files/9628406/Create.project.and.assign.blocks.docx)

**Comment by bastianbc** [comment]
I hope this makes sense. Please let me know if questions/comments.

**Comment by ceylanbagci** [comment]
I got your doc file read and commit few minutes
